### ISSUE TITLE
JF becomes slow after a while

### ISSUE THREAD

**Issue by TobiasDeBruijn** [CTalvio/Monochromic#10] opened 2020-10-13 11:22 UTC
Hey!
First of all, love the theme! Thank you so much for your hard work!

I have noticed a little thing though, which I did not notice when using the standard JF CSS. If you load the site up (or refresh it) it's all nice and fast, but if I go do something else and then come back to the Jellyfin site, it is quite slow and not as snappy. I'm not sure what in this 'theme' could cause this, but maybe you do.

I use the high performance 'module' ontop of the base.

Jellyfin Version: 10.6.4
Host platform: x64
Platform with the issue: desktop. Chrome 85.0.4183.12

Hope you're able to do something about it :D
Thanks!

**Comment by CTalvio** [comment] 2020-10-13 21:39
Huh.                     Weird. 

I keep a JF tab open at all times. Whatever this is, it's not significant enough for me to have noticed myself, but you seem to maybe, be right. How large is the difference? How long does it take for it to set in? I can only notice a difference so slight I'm not sure it's there. But my machine is very high end so the problem may be worse on the average PC or mobile device.

I have NO clue what might be causing it. Would have to experiment. If you'd be willing to test possible fixes, that would be great. When I get around to looking at it, I'd post import lines here for a couple different versions with possible culprits addressed, and then you could see if any of them fixes it.

**Comment by TobiasDeBruijn** [comment] 2020-10-14 14:26
After some short testing it seems to set it after roughly 10 minutes of working in a different Chrome window. It does recover--ish, it gets a bit faster again but not the same as a full reload.

I don't think it's my hardware, I'm running a 7700K, 2080Ti and 32Gb of ram. So that should be more than plenty

Server is a Supermicro X9 running 2x Xeon E5-2630L v2 @2.4 Ghz, 96GB ram. Running Ubuntu (20.04), with JF in an LXC.

I'm more than happy to test possible fixes yeah :D

**Comment by CTalvio** [comment] 2020-10-14 18:49
Ok. Then it should be safe to assume hardware is not a factor. I don't have to worry about that particular variable. Yay. I use Firefox, so just installed chrome and will try to replicate.

**Comment by CTalvio** [comment] 2020-10-14 20:48
I can't get it to slow down in chrome. So you will have to test. My first hunch is the use of mask-image. Use the below line instead of default_style. Also remove the performance add-on. This test essentially makes so mask image is never there, not even used and then disabled by the add-on. 

`@import url('https://ctalvio.github.io/Monochromic/test_style.css');`

**Comment by TobiasDeBruijn** [comment] 2020-10-15 14:13
That unfortunately has not solved it. CSS is as follows currently:
```
/*@import url('https://ctalvio.github.io/Monochromic/default_style.css');
@import url('https://ctalvio.github.io/Monochromic/improve-performance_style.css');*/

@import url('https://ctalvio.github.io/Monochromic/test_style.css');
```

Looking at task manager, Chrome will go up to as high as 60% CPU usage when trying to scroll on Jellyfin. Ram usage is normal though.

**Comment by TobiasDeBruijn** [comment] 2020-10-15 14:38
Did some more checking and testing. The slow down does not occur when in the dashboard.

**Comment by CTalvio** [comment] 2020-10-15 20:53
Alright, what if you copy [test_style.css](https://github.com/CTalvio/Monochromic/blob/master/test_style.css) into the Custom CSS field without using `@import`?

If it still happens then, you can test by deleting sections of code. I really have no clue at all about what could be causing it, and it does not occur on my machine, so I'm stumped in coming up with other ways to find the issue.

My suggestion would be to divide it in places where I have commented what a section does, as that should let you take the theme apart in discrete parts. I edited the comments in test_style a bit further to facilitate this. Try it one section at a time, or half and half to eliminate code without issue, then divide the half with the issue further and further until you narrow it to a single section.

**Comment by TobiasDeBruijn** [comment] 2020-10-15 22:09
WIll give that a go. Will also give MS Edge a go, since Chrome has started cutting up the URL. WIll report back in a couple of days hopefully :)

**Comment by TobiasDeBruijn** [comment] 2020-10-20 07:46
Interesting find so far, the issue doesn't exist on Edge Chromium, neither does it happen on Firefox. Seems to be isolated to Chrome. Extensions on Edge Chromium and Chrome are the same, so it's unlikely that an extension causes it. But just to be sure, a list of the extensions I use:
- LastPass
- Honey
- AdBlock Plus
- uBlock
- uBlock Origin
- GitHub Gloc
- AudioPick

**Comment by GeorgeGedox** [comment] 2020-10-22 04:29
@TheDutchMC this has nothing to do with the theme, the browser or your hardware, it's the extensions you use, you have 3 adblockers and one very privacy intrusive extension, AdBlock Plus, uBlock and uBlock Origin clash with eachother, use one, and I really suggest you do some research on which one to keep because 2 of them are very close to being malware at this point.

Now Honey, I'm not sure you know but this extension will keep processing any tab you have open nearly every second searching for inputs and processing some data such as what's the url, trying to find info about the domain and so on, this in combination with the clashes caused by the adblockers will lead to slowdowns.

If you want to test this just install plain Chromium directly from github, no extensions and try reproducing the issue.

**Comment by TobiasDeBruijn** [comment] 2020-10-22 06:09
I already guessed it was extensions yeah. Interestingly enough though, I use the same extensions on Chromium Edge, where the issue doesn't occur.

**Comment by CTalvio** [comment] 2020-10-23 10:30
Chromium is just the base. Edge has AGGRESSIVE background optimizations as Microsoft prioritizes maximum battery life where other browsers are known to be less efficient. That may be the reason you aren't seeing it in Edge, as Edge is detecting and shutting down excess extension activity in the background.

Please try uninstalling/disabling extensions to see if the problem remains.

**Comment by CTalvio** [comment] 2020-11-09 21:07
Closing as this is very unlikely to be a theme side issue.

**Closed as completed by CTalvio** 2020-11-09 21:07 UTC
